### ISSUE TITLE
feat: 📦 Screen: My Plants

### ISSUE THREAD

**Issue by Chocolatamargo2607** [Chocolatamargo2607/UD.PPC.MyPlantSitter#2]
# Requierements
## Mockup
🔗 [Link](https://excalidraw.com/#room=20312337fc2180a0a6c3,9LA3NsRTg0xzP2Inpw6lww)
## Task
- [x] Style: ✨ Create list: It will do contain the plants
- [x] Style: ✨ Create button 'Register plant'

**Comment by SP3KTRO** [comment]
Done
